export const bibleBooks = {
  oldTestament: [
    { name: "Génesis", slug: "genesis" },
    { name: "Éxodo", slug: "exodus" },
    { name: "Levítico", slug: "leviticus" },
    { name: "Números", slug: "numbers" },
    { name: "Deuteronomio", slug: "deuteronomy" },
    { name: "Josué", slug: "joshua" },
    { name: "Jueces", slug: "judges" },
    { name: "Rut", slug: "ruth" },
    { name: "1 Samuel", slug: "1-samuel" },
    { name: "2 Samuel", slug: "2-samuel" },
    { name: "1 Reyes", slug: "1-kings" },
    { name: "2 Reyes", slug: "2-kings" },
    { name: "1 Crónicas", slug: "1-chronicles" },
    { name: "2 Crónicas", slug: "2-chronicles" },
    { name: "Esdras", slug: "ezra" },
    { name: "Nehemías", slug: "nehemiah" },
    { name: "Ester", slug: "esther" },
    { name: "Job", slug: "job" },
    { name: "Salmos", slug: "psalms" },
    { name: "Proverbios", slug: "proverbs" },
    { name: "Eclesiastés", slug: "ecclesiastes" },
    { name: "Cantares", slug: "song-of-solomon" },
    { name: "Isaías", slug: "isaiah" },
    { name: "Jeremías", slug: "jeremiah" },
    { name: "Lamentaciones", slug: "lamentations" },
    { name: "Ezequiel", slug: "ezekiel" },
    { name: "Daniel", slug: "daniel" },
    { name: "Oseas", slug: "hosea" },
    { name: "Joel", slug: "joel" },
    { name: "Amós", slug: "amos" },
    { name: "Abdías", slug: "obadiah" },
    { name: "Jonás", slug: "jonah" },
    { name: "Miqueas", slug: "micah" },
    { name: "Nahúm", slug: "nahum" },
    { name: "Habacuc", slug: "habakkuk" },
    { name: "Sofonías", slug: "zephaniah" },
    { name: "Hageo", slug: "haggai" },
    { name: "Zacarías", slug: "zechariah" },
    { name: "Malaquías", slug: "malachi" },
  ],
  newTestament: [
    { name: "Mateo", slug: "matthew" },
    { name: "Marcos", slug: "mark" },
    { name: "Lucas", slug: "luke" },
    { name: "Juan", slug: "john" },
    { name: "Hechos", slug: "acts" },
    { name: "Romanos", slug: "romans" },
    { name: "1 Corintios", slug: "1-corinthians" },
    { name: "2 Corintios", slug: "2-corinthians" },
    { name: "Gálatas", slug: "galatians" },
    { name: "Efesios", slug: "ephesians" },
    { name: "Filipenses", slug: "philippians" },
    { name: "Colosenses", slug: "colossians" },
    { name: "1 Tesalonicenses", slug: "1-thessalonians" },
    { name: "2 Tesalonicenses", slug: "2-thessalonians" },
    { name: "1 Timoteo", slug: "1-timothy" },
    { name: "2 Timoteo", slug: "2-timothy" },
    { name: "Tito", slug: "titus" },
    { name: "Filemón", slug: "philemon" },
    { name: "Hebreos", slug: "hebrews" },
    { name: "Santiago", slug: "james" },
    { name: "1 Pedro", slug: "1-peter" },
    { name: "2 Pedro", slug: "2-peter" },
    { name: "1 Juan", slug: "1-john" },
    { name: "2 Juan", slug: "2-john" },
    { name: "3 Juan", slug: "3-john" },
    { name: "Judas", slug: "jude" },
    { name: "Apocalipsis", slug: "revelation" },
  ],
};

export const bibleBookAbbrevBySlug: { [key: string]: string } = {
  genesis: "gn",
  exodus: "ex",
  leviticus: "lv",
  numbers: "nm",
  deuteronomy: "dt",
  joshua: "js",
  judges: "jud",
  ruth: "rt",
  "1-samuel": "1sm",
  "2-samuel": "2sm",
  "1-kings": "1kgs",
  "2-kings": "2kgs",
  "1-chronicles": "1ch",
  "2-chronicles": "2ch",
  ezra: "ezr",
  nehemiah: "ne",
  esther: "et",
  job: "job",
  psalms: "ps",
  proverbs: "prv",
  ecclesiastes: "ec",
  "song-of-solomon": "so",
  isaiah: "is",
  jeremiah: "jr",
  lamentations: "lm",
  ezekiel: "ez",
  daniel: "dn",
  hosea: "ho",
  joel: "jl",
  amos: "am",
  obadiah: "ob",
  jonah: "jn",
  micah: "mi",
  nahum: "na",
  habakkuk: "hk",
  zephaniah: "zp",
  haggai: "hg",
  zechariah: "zc",
  malachi: "ml",
  matthew: "mt",
  mark: "mk",
  luke: "lk",
  john: "jo",
  acts: "act",
  romans: "rm",
  "1-corinthians": "1co",
  "2-corinthians": "2co",
  galatians: "gl",
  ephesians: "eph",
  philippians: "ph",
  colossians: "cl",
  "1-thessalonians": "1ts",
  "2-thessalonians": "2ts",
  "1-timothy": "1tm",
  "2-timothy": "2tm",
  titus: "tt",
  philemon: "phm",
  hebrews: "hb",
  james: "jm",
  "1-peter": "1pe",
  "2-peter": "2pe",
  "1-john": "1jo",
  "2-john": "2jo",
  "3-john": "3jo",
  jude: "jd",
  revelation: "re",
};

export const bibleBookNameBySlug: { [key: string]: string } = {
  genesis: "Génesis",
  exodus: "Éxodo",
  leviticus: "Levítico",
  numbers: "Números",
  deuteronomy: "Deuteronomio",
  joshua: "Josué",
  judges: "Jueces",
  ruth: "Rut",
  "1-samuel": "1 Samuel",
  "2-samuel": "2 Samuel",
  "1-kings": "1 Reyes",
  "2-kings": "2 Reyes",
  "1-chronicles": "1 Crónicas",
  "2-chronicles": "2 Crónicas",
  ezra: "Esdras",
  nehemiah: "Nehemías",
  esther: "Ester",
  job: "Job",
  psalms: "Salmos",
  proverbs: "Proverbios",
  ecclesiastes: "Eclesiastés",
  "song-of-solomon": "Cantares",
  isaiah: "Isaías",
  jeremiah: "Jeremías",
  lamentations: "Lamentaciones",
  ezekiel: "Ezequiel",
  daniel: "Daniel",
  hosea: "Oseas",
  joel: "Joel",
  amos: "Amós",
  obadiah: "Abdías",
  jonah: "Jonás",
  micah: "Miqueas",
  nahum: "Nahúm",
  habakkuk: "Habacuc",
  zephaniah: "Sofonías",
  haggai: "Hageo",
  zechariah: "Zacarías",
  malachi: "Malaquías",
  matthew: "Mateo",
  mark: "Marcos",
  luke: "Lucas",
  john: "Juan",
  acts: "Hechos",
  romans: "Romanos",
  "1-corinthians": "1 Corintios",
  "2-corinthians": "2 Corintios",
  galatians: "Gálatas",
  ephesians: "Efesios",
  philippians: "Filipenses",
  colossians: "Colosenses",
  "1-thessalonians": "1 Tesalonicenses",
  "2-thessalonians": "2 Tesalonicenses",
  "1-timothy": "1 Timoteo",
  "2-timothy": "2 Timoteo",
  titus: "Tito",
  philemon: "Filemón",
  hebrews: "Hebreos",
  james: "Santiago",
  "1-peter": "1 Pedro",
  "2-peter": "2 Pedro",
  "1-john": "1 Juan",
  "2-john": "2 Juan",
  "3-john": "3 Juan",
  jude: "Judas",
  revelation: "Apocalipsis",
};
