export const librosBiblia = {
    antiguoTestamento: [
      { nombre: "Génesis", slug: "genesis" },
      { nombre: "Éxodo", slug: "exodo" },
      { nombre: "Levítico", slug: "levitico" },
      { nombre: "Números", slug: "numeros" },
      { nombre: "Deuteronomio", slug: "deuteronomio" },
      { nombre: "Josué", slug: "josue" },
      { nombre: "Jueces", slug: "jueces" },
      { nombre: "Rut", slug: "rut" },
      { nombre: "1 Samuel", slug: "1-samuel" },
      { nombre: "2 Samuel", slug: "2-samuel" },
      { nombre: "1 Reyes", slug: "1-reyes" },
      { nombre: "2 Reyes", slug: "2-reyes" },
      { nombre: "1 Crónicas", slug: "1-cronicas" },
      { nombre: "2 Crónicas", slug: "2-cronicas" },
      { nombre: "Esdras", slug: "esdras" },
      { nombre: "Nehemías", slug: "nehemias" },
      { nombre: "Ester", slug: "ester" },
      { nombre: "Job", slug: "job" },
      { nombre: "Salmos", slug: "salmos" },
      { nombre: "Proverbios", slug: "proverbios" },
      { nombre: "Eclesiastés", slug: "eclesiastes" },
      { nombre: "Cantares", slug: "cantares" },
      { nombre: "Isaías", slug: "isaias" },
      { nombre: "Jeremías", slug: "jeremias" },
      { nombre: "Lamentaciones", slug: "lamentaciones" },
      { nombre: "Ezequiel", slug: "ezequiel" },
      { nombre: "Daniel", slug: "daniel" },
      { nombre: "Oseas", slug: "oseas" },
      { nombre: "Joel", slug: "joel" },
      { nombre: "Amós", slug: "amos" },
      { nombre: "Abdías", slug: "abdias" },
      { nombre: "Jonás", slug: "jonas" },
      { nombre: "Miqueas", slug: "miqueas" },
      { nombre: "Nahúm", slug: "nahum" },
      { nombre: "Habacuc", slug: "habacuc" },
      { nombre: "Sofonías", slug: "sofonias" },
      { nombre: "Hageo", slug: "hageo" },
      { nombre: "Zacarías", slug: "zacarias" },
      { nombre: "Malaquías", slug: "malaquias" },
    ],
    nuevoTestamento: [
      { nombre: "Mateo", slug: "mateo" },
      { nombre: "Marcos", slug: "marcos" },
      { nombre: "Lucas", slug: "lucas" },
      { nombre: "Juan", slug: "juan" },
      { nombre: "Hechos", slug: "hechos" },
      { nombre: "Romanos", slug: "romanos" },
      { nombre: "1 Corintios", slug: "1-corintios" },
      { nombre: "2 Corintios", slug: "2-corintios" },
      { nombre: "Gálatas", slug: "galatas" },
      { nombre: "Efesios", slug: "efesios" },
      { nombre: "Filipenses", slug: "filipenses" },
      { nombre: "Colosenses", slug: "colosenses" },
      { nombre: "1 Tesalonicenses", slug: "1-tesalonicenses" },
      { nombre: "2 Tesalonicenses", slug: "2-tesalonicenses" },
      { nombre: "1 Timoteo", slug: "1-timoteo" },
      { nombre: "2 Timoteo", slug: "2-timoteo" },
      { nombre: "Tito", slug: "tito" },
      { nombre: "Filemón", slug: "filemon" },
      { nombre: "Hebreos", slug: "hebreos" },
      { nombre: "Santiago", slug: "santiago" },
      { nombre: "1 Pedro", slug: "1-pedro" },
      { nombre: "2 Pedro", slug: "2-pedro" },
      { nombre: "1 Juan", slug: "1-juan" },
      { nombre: "2 Juan", slug: "2-juan" },
      { nombre: "3 Juan", slug: "3-juan" },
      { nombre: "Judas", slug: "judas" },
      { nombre: "Apocalipsis", slug: "apocalipsis" },
    ],
  }
  
  export const abreviaturasLibrosPorSlug = {
    genesis: "gn",
    exodo: "ex",
    levitico: "lv",
    numeros: "nm",
    deuteronomio: "dt",
    josue: "js",
    jueces: "jue",
    rut: "rt",
    "1-samuel": "1sm",
    "2-samuel": "2sm",
    "1-reyes": "1rey",
    "2-reyes": "2rey",
    "1-cronicas": "1cr",
    "2-cronicas": "2cr",
    esdras: "ezr",
    nehemias: "neh",
    ester: "est",
    job: "job",
    salmos: "sal",
    proverbios: "prv",
    eclesiastes: "ec",
    cantares: "can",
    isaias: "isa",
    jeremias: "jer",
    lamentaciones: "lam",
    ezequiel: "eze",
    daniel: "dan",
    oseas: "ose",
    joel: "joe",
    amos: "amo",
    abdias: "abd",
    jonas: "jon",
    miqueas: "miq",
    nahum: "nah",
    habacuc: "hab",
    sofonias: "sof",
    hageo: "hag",
    zacarias: "zac",
    malaquias: "mal",
    mateo: "mat",
    marcos: "mar",
    lucas: "luc",
    juan: "juan",
    hechos: "hech",
    romanos: "rom",
    "1-corintios": "1cor",
    "2-corintios": "2cor",
    galatas: "gal",
    efesios: "ef",
    filipenses: "fil",
    colosenses: "col",
    "1-tesalonicenses": "1tes",
    "2-tesalonicenses": "2tes",
    "1-timoteo": "1tim",
    "2-timoteo": "2tim",
    tito: "tit",
    filemon: "file",
    hebreos: "heb",
    santiago: "sant",
    "1-pedro": "1ped",
    "2-pedro": "2ped",
    "1-juan": "1juan",
    "2-juan": "2juan",
    "3-juan": "3juan",
    judas: "jud",
    apocalipsis: "apoc",
  }
  
  export const nombreLibroPorSlug = {
    genesis: "Génesis",
    exodo: "Éxodo",
    levitico: "Levítico",
    numeros: "Números",
    deuteronomio: "Deuteronomio",
    josue: "Josué",
    jueces: "Jueces",
    rut: "Rut",
    "1-samuel": "1 Samuel",
    "2-samuel": "2 Samuel",
    "1-reyes": "1 Reyes",
    "2-reyes": "2 Reyes",
    "1-cronicas": "1 Crónicas",
    "2-cronicas": "2 Crónicas",
    esdras: "Esdras",
    nehemias: "Nehemías",
    ester: "Ester",
    job: "Job",
    salmos: "Salmos",
    proverbios: "Proverbios",
    eclesiastes: "Eclesiastés",
    cantares: "Cantares",
    isaias: "Isaías",
    jeremias: "Jeremías",
    lamentaciones: "Lamentaciones",
    ezequiel: "Ezequiel",
    daniel: "Daniel",
    oseas: "Oseas",
    joel: "Joel",
    amos: "Amós",
    abdias: "Abdías",
    jonas: "Jonás",
    miqueas: "Miqueas",
    nahum: "Nahúm",
    habacuc: "Habacuc",
    sofonias: "Sofonías",
    hageo: "Hageo",
    zacarias: "Zacarías",
    malaquias: "Malaquías",
    mateo: "Mateo",
    marcos: "Marcos",
    lucas: "Lucas",
    juan: "Juan",
    hechos: "Hechos",
    romanos: "Romanos",
    "1-corintios": "1 Corintios",
    "2-corintios": "2 Corintios",
    galatas: "Gálatas",
    efesios: "Efesios",
    filipenses: "Filipenses",
    colosenses: "Colosenses",
    "1-tesalonicenses": "1 Tesalonicenses",
    "2-tesalonicenses": "2 Tesalonicenses",
    "1-timoteo": "1 Timoteo",
    "2-timoteo": "2 Timoteo",
    tito: "Tito",
    filemon: "Filemón",
    hebreos: "Hebreos",
    santiago: "Santiago",
    "1-pedro": "1 Pedro",
    "2-pedro": "2 Pedro",
    "1-juan": "1 Juan",
    "2-juan": "2 Juan",
    "3-juan": "3 Juan",
    judas: "Judas",
    apocalipsis: "Apocalipsis",
  }
  